theme: jekyll-theme-cayman
permalink: "/:title/"
baseurl: "/bashwizard.com"
defaults:
  -
    scope:
      path: "/_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
